# Generated by Django 5.1.1 on 2025-01-06 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Cinema', max_length=100)),
                ('city', models.CharField(default='Unknown City', max_length=100)),
                ('address', models.TextField(default='Unknown Address')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.URLField()),
                ('runtime', models.PositiveIntegerField(help_text='Runtime in minutes')),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=20)),
                ('synopsis', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('cast', models.TextField(help_text='Comma-separated list of cast members')),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('format', models.CharField(max_length=20)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.movie')),
            ],
        ),
    ]
