# Generated by Django 5.1.1 on 2025-02-18 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cinema')),
            ],
        ),
        migrations.AddField(
            model_name='showtime',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cinemahall'),
        ),
    ]
