# Generated by Django 5.1.1 on 2025-04-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cinemahall_showtime_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='nowPlaying',
            field=models.BooleanField(default=False, help_text='Is the movie currently playing?'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default='https://www.youtube.com/watch?v=BpJYNVhGf1s'),
        ),
    ]
