# Generated by Django 5.1.1 on 2025-04-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_movie_nowplaying_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ageRating',
            field=models.CharField(default='PG-13', help_text='Age rating (e.g., PG-13)', max_length=10),
        ),
    ]
