# Generated by Django 5.1.1 on 2024-12-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='poster',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
